#Loads data in a usable format from original txt file (from working directory)
power=read.table("household_power_consumption.txt", header = TRUE, sep = ";")
power$Date <- as.Date(as.factor(power$Date),format="%d/%m/%Y")
pow <- subset(power, Date==as.Date("2007-02-01") | Date==as.Date("2007-02-02"))
pow$Date <- as.factor(pow$Date)
pow$DateTime <- strptime(paste(pow$Date, pow$Time), format="%Y-%m-%d %H:%M:%S")
pow$Global_active_power=as.numeric(as.character(pow$Global_active_power)
pow$Global_reactive_power=as.numeric(as.character(pow$Global_reactive_power))
pow$Voltage=as.numeric(as.character(pow$Voltage))

#Plots DateTime vs Sub Metering
png('plot3.png',width=480,height=480)
par(col="black")
plot(pow$DateTime,pow$Sub_metering_1,ylab="Energy sub metering",xlab="",type='l')
par(col="red")
lines(pow$DateTime,pow$Sub_metering_2,ylab="Energy sub metering",xlab="",type='l')
par(col="blue")
lines(pow$DateTime,pow$Sub_metering_3,ylab="Energy sub metering",xlab="",type='l')
plot.window(c(0,480),c(0,480))
legend(325,500,c("Sub metering 1","Sub metering 2","Sub metering 3"), lty=c(1,1,1), col=c("black","red","blue"))
dev.off()